### ISSUE TITLE
remote url download 

### ISSUE THREAD

**Issue by Sarfroz** [bandwidth-throttle/bandwidth-throttle#2]
how can we implement same for the remote url file download
Like a file in server A and we to download it using server B using stream download with resume

**Comment by malkusch** [comment]
Sorry, I have problems understanding your question. Could you please explain a bit more what you want to achieve?

**Comment by Sarfroz** [comment]
sir, lets say there is already a download link 
https://www.abc.com/xyz.mp4
now i want to download via my server so how can I achieve it. it's more proxyifying download links via my server.

**Comment by malkusch** [comment]
And you want to throttle the download from your server? Well, isn't this exactly the first example in the Readme?

**Comment by Sarfroz** [comment]
no sir you are saving file to disk then allowing them to download, what I am speaking is of download as the stream .

**Comment by malkusch** [comment]
That first example reads a file from disk, that's right and copies that to stdout. Please instead of reading the file from the disk, you can use an URL as well.

**Comment by Sarfroz** [comment]
okey sir i will try and let you know.
